CREATE DATABASE IMAGE_SITE;
USE IMAGE_SITE;
CREATE TABLE IMAGES(
I_ID CHAR(60) PRIMARY KEY,
U_DATE DATE NOT NULL,SIZE INT,
VISIBLE VARCHAR(3) NOT NULL,
I_NAME VARCHAR(80) NOT NULL,
U_ID VARCHAR(30)
);
CREATE TABLE IMG_KEYWORDS(
ID CHAR(60) PRIMARY KEY,
 I_ID CHAR(60) NOT NULL ,
 CONSTRAINT `fk_I_ID` FOREIGN KEY (I_ID) REFERENCES IMAGES(I_ID) ON DELETE CASCADE,
 KEYWORD VARCHAR(50)
 );
CREATE TABLE USERS(
NAME_ID VARCHAR(30) PRIMARY KEY,
PASSWD CHAR(60) NOT NULL,
EMAIL VARCHAR(60) UNIQUE NOT NULL,
DOJ DATE NOT NULL, L_IP INT,
PRO_IMG CHAR(60),
CONSTRAINT `fk_PRO_IMG` FOREIGN KEY (PRO_IMG) REFERENCES IMAGES(I_ID)
);

ALTER TABLE IMAGES ADD CONSTRAINT `fk_U_ID` FOREIGN KEY (U_ID) REFERENCES USERS(NAME_ID) ON DELETE CASCADE;

ALTER TABLE users ADD  VERIFIED BOOL AFTER PRO_IMG;

SELECT * FROM USERS AS u, IMAGES AS I, IMG_KEYWORDS AS IK;

SELECT * FROM users;
INSERT INTO  users(NAME_ID, PASSWD,EMAIL) VALUES('abhirup27','ABHIrup_27','abhirup27022001@outlook.com');

DELETE FROM users WHERE NAME_ID = 'abhi22rup238922'

SELECT NAME_ID,EMAIL FROM users WHERE NAME_ID = 'abhirup289' OR EMAIL = 'abhirup27022001@outlook.com'

SELECT CASE WHEN COUNT(NAME_ID) >=1 THEN CAST(1 AS binary)
ELSE
CAST(0 AS binary)
FROM users
WHERE NAME_ID = 'abhirup27' 

SELECT CASE IF( SELECT COUNT(NAME_ID) FROM users WHERE NAME_ID = 'abhirup27') >=1 THEN CAST(1 AS BINARY) ELSE CAST(0 AS BINARY);  

SELECT CASE WHEN EXISTS(
	SELECT * FROM users WHERE NAME_ID = 'abhirup289' OR EMAIL = 'abhirup27022001@outlook.com'
)
THEN CAST(1 AS INT)
ELSE CAST(0 AS INT)  END  AS 'FOUND' 

       